### PR TITLE
feat: Object spooner.

### PR DESCRIPTION
**Pull request by tupoy-ya**
## Reason
Object Spooner is useful for debugging and also pretty fun to play with.

## Additional context
- [x] Mouse Object Spooner.
- [x] Basic Object Spooner.
- [x] View - set object properties.
- [ ] Entity database.

### CODE REVIEW

**Comment by Gh0sSte** [comment]
before adding object spawning maybe you should add an object pool? Since if you reach above a certain amount of objects the game crashes...

**Comment by TheGreenBandit** [comment]
As loko said it would be smart to add a check bool objpoolfilled g_object_pool->g_objects or whatever it is > g_max_objects -100; return objpoolfilled = true;
Else return objpoolfilled = false;

if(!objpoolfilled)
{
Function
}

Something like this

**Comment by iswaxan** [comment]
there are slose to all in this website https://gtahash.ru/ but i think ya already got here

**Comment by tupoy-ya** [comment]
The website has nothing to do with Object Spooner, and i want to have an in game menu like in Gmod which is very hard to implement for a moron like me.

Also this PR will probably be closed and rebased on the lite branch when i consider it stable.

**Comment by iswaxan** [comment]
oh, k

**Comment by tupoy-ya** [comment]
Stale PR.

**Pull request closed without merging**
