### PR TITLE
fix(coloading): Load with original YimMenu.

### PR DESCRIPTION
**Pull request by TheGreenBandit**
also tried moving the notification to above map for when it loads but i get an error for to many arguments

- [x] fix arguments error
- [x] add image
- [ ] get image to disappear with text
- [x] fix text staying

### CODE REVIEW

**Comment by TheGreenBandit** [comment]
also we should try drawing an black image above the loading part as an example if u ever want to come up with an image

**Comment by tupoy-ya** [comment]
> also we should try drawing an black image above the loading part as an example if u ever want to come up with an image

What loading screen, what image?

**Comment by TheGreenBandit** [comment]
- [ ] 

> > also we should try drawing an black image above the loading part as an example if u ever want to come up with an image
> 
> What loading screen, what image? 

yeah like have that image above the loaded text

**Comment by TheGreenBandit** [comment]
added u as collaborater on fork i made this way u can push commits

**Comment by tupoy-ya** [comment]
> added u as collaborater on fork i made this way u can push commits

I already can because of
image

**Comment by tupoy-ya** [comment]
I will try working on this when i finish https://github.com/YimMenu/YimMenu/pull/551

**Comment by TheGreenBandit** [comment]
> > added u as collaborater on fork i made this way u can push commits
> 
> I already can because of image

ah just wanted to make sure anyways lmao

**Comment by TheGreenBandit** [comment]
Also check out https://github.com/YimMenu/YimMenu/issues/549 for extra spoofing ideas

**Comment by TheGreenBandit** [comment]
> treated as error?
In the most recent commit i pushed i got rid of the argument error but now the fix i have done is treated as a error for some reason

**Comment by TheGreenBandit** [comment]
Figured out the warning it's treating as errors,

>function call missing argument list gui.cpp line 155

>discarding return value of function with nodiscard attribute gui.cpp line 155

**Comment by TheGreenBandit** [comment]
finally fixed it by messing around with the code, now i have no clue how to do the image part

**Comment by TheGreenBandit** [comment]
one thing i would also like todo is make a asi folder if there is not one already made, as right now you have to make the folder yourself.

**Comment by TheGreenBandit** [comment]
in this commit we were trying to get a countdown to have the image disappear, also fixed a lot

**Comment by tupoy-ya** [comment]
How about not add `NativeUI` here.

**Comment by tupoy-ya** [comment]
Some questions about this PR:
- How do you want to download this `tupoye.ytd`?
- Why don't add it to ImGui notification instead?
- If you add it to ImGui how do you want to download `logo.png`?
- Is this PR about changing loading notification to use `native_ui` for some reason, or renaming folders to `TupoyeMenu`, or supporting coloading with original YimMenu which i don't even think is possible?

**Comment by TheGreenBandit** [comment]
> Some questions about this PR:
> 
> * How do you want to download this `tupoye.ytd`?
> * Why don't add it to ImGui notification instead?
> * If you add it to ImGui how do you want to download `logo.png`?
> * Is this PR about changing loading notification to use `native_ui` for some reason, or renaming folders to `TupoyeMenu`, or supporting coloading with original YimMenu which i don't even think is possible?

idk, we were tired and did t this way

**Pull request closed without merging**
