### PR TITLE
chore: Merge YimMenu (Update for 3095).

### PR DESCRIPTION
**Pull request by tupoy-ya**
- [x] Test in SP.
- [x] Test in MP.

Could not connect to a public session for some reason, everything else i tried worked.

EDIT: Removing checksum settings seems to have fixed the public session joining issue.
Didn't try to load any rpf mods yet.

### CODE REVIEW

**Comment by tupoy-ya** [comment]
@SlavicBlin Can you test if seamless join works for you?

**Comment by SlavicBlin** [comment]
> @SlavicBlin Can you test if seamless join works for you?

Yeah okay give me like 5 mins

**Comment by SlavicBlin** [comment]
> @SlavicBlin Can you test if seamless join works for you?

Seems to be working fine

**Comment by tupoy-ya** [comment]
> Seems to be working fine

Thanks for testing.

**Pull request merged**
